language: python
python:
  - { PATH: "{{replace(Python35, '\\', '\\\\')}}", VERSION: 3.5, DIST: std }
  - { PATH: "{{replace(Anaconda3, '\\', '\\\\')}}", VERSION: 3.5, DIST: conda }
  - { PATH: "{{replace(WinPython35, '\\', '\\\\')}}", VERSION: 3.5, DIST: winpython }
virtualenv:
  - path: {{ospathjoin(root_path, pickname("%NAME_JENKINS%", project_name + "_%VERSION%_%DIST%_%NAME%"), "_venv")}}
install:
  - pip install --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper pyensae pymmails pymyinstall pyrsslocal
  - pip install -r requirements.txt
  - pip freeze
script:
  - { CMD: "python setup.py unittests", NAME: "UT" }
  - { CMD: "python setup.py unittests_LONG", NAME: "UT_LONG", TIMEOUT: 2400 }
  - { CMD: "python setup.py unittests_SKIP", NAME: "UT_SKIP" }
  - { CMD: "python setup.py unittests -g .*_1A_.*", NAME: "UT_1A" }
  - { CMD: "python setup.py unittests -g .*_2A_.*", NAME: "UT_2A" }
  - { CMD: "python setup.py unittests -g .*_3A_.*", NAME: "UT_3A" }
  - { CMD: "python setup.py unittests -g .*_EX_.*", NAME: "UT_EX" }
  - if [ ${VERSION} == "3.5" and ${DIST} == "std" ]
      then 
        --CMD=python setup.py build_sphinx;
        --NAME=DOC;
      fi  
after_script:
  - python setup.py bdist_wheel
  - if [ ${DIST} != "conda" and ${VERSION} != "3.4" and ${NAME} == "UT" ] then copy dist\*.whl ..\..\local_pypi\local_pypi_server fi
documentation:
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then python setup.py build_pres fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then python setup.py build_pres_2A fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then python setup.py build_pres_3A fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then python setup.py build_pres_1Ap fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} == "UT" ] then python setup.py build_sphinx fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build\html dist\html fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build2\html dist\html2 fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\sphinxdoc\build3\html dist\html3 fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_projets\a2015\build\html dist\html_pres_1Ap\2015 fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_projets\a2016\build\html dist\html_pres_1Ap fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_2A\build\html dist\html_pres_2A fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation_3A\build\html dist\html_pres_3A fi
  - if [ ${PYTHON} == "{{Python35}}" and ${NAME} in {"UT", "DOC"} ] then xcopy /E /C /I /Y _doc\presentation\build\html dist\html_pres fi
