language: python
python:
    - "3.4"
    - "3.5"
before_install:
    - sudo apt-get install -qq gcc liblapack-dev
install: 
    - pip install -r requirements.txt
    - pip install -r requirements_ext.txt
script:
    - python setup.py unittests
