language: python
python:
    - "3.4"
before_install:
  - pip install sympy --use-mirrors
  - pip install numpy --use-mirrors
  - sudo apt-get install python-cvxopt
  - sudo apt-get build-dep python-cvxopt
  - pip install cvxopt --use-mirrors
  - sudo apt-get install python-scipy
  - pip install coveralls --use-mirrors
install: 
    - pip install -r requirements.txt
script:
    - python setup.py unittests
